export const keys = [
  // 134
  "total_alimentacao",
  "total_alimentacao_no_domicilio",
  "cereais_leguminosas_e_oleaginosas",
  "farinhas_feculas_e_massas",
  "tuberculos_raizes_e_legumes",
  "acucares_e_derivados",
  "hortalicas_e_verduras",
  "frutas",
  "carnes",
  "pescados",
  "carnes_e_peixes_industrializados",
  "aves_e_ovos",
  "leites_e_derivados",
  "panificados",
  "oleos_e_gorduras",
  "bebidas_e_infusoes",
  "enlatados_e_conservas",
  "sal_e_condimentos",
  "leite_de_coco",
  "atomatado",
  "alho",
  "sal",
  "sal_grosso",
  "colorau",
  "caldo_de_tucupi",
  "fermento",
  "maionese",
  "vinagre_de_alcool",
  "vinagre",
  "salsa_desidratada",
  "misso",
  "caldo_concentrado",
  "pimenta_em_po",
  "cominho",
  "fondor",
  "amaciante_de_carne",
  "sal_dietetico",
  "hortela",
  "pimenta_do_reino",
  "curry",
  "molho_de_tucupi_com_pimenta",
  "sal_amoniaco",
  "tempero_misto",
  "bicarbonato_de_sodio",
  "glutamato_monossodico",
  "baunilha_em_po",
  "canela_em_po",
  "cravo",
  "paprica",
  "noz_moscada",
  "mostarda",
  "louro",
  "acafrao_em_po",
  "gengibre",
  "alfavaca",
  "oregano",
  "alcaparra",
  "manjerona",
  "coentro",
  "alho_em_po",
  "cebola_em_po",
  "cheiro_verde_em_po",
  "pimentao_em_po",
  "vinagre_de_maca",
  "molho_de_soja",
  "molho_ingles",
  "molho_tartaro",
  "molho_branco",
  "caldo_de_queijo",
  "molho_nao_especificado",
  "coalho",
  "sal_amargo",
  "salvia_em_folha",
  "erva_doce",
  "tomilho_em_folha",
  "vinagre_de_arroz",
  "vinagre_de_milho",
  "gergelim_em_po",
  "tempero_de_saladas",
  "molho_xadrez",
  "molho_de_funghi",
  "molho_de_alho",
  "molho_de_pimenta",
  "molho_madeira",
  "molho_para_salada",
  "molho_agridoce",
  "molho_barbecue",
  "molho_de_frango",
  "molho_para_carne",
  "molho_temperado_parmesao",
  "pimenta_calabresa",
  "vinagre_de_limao",
  "vinagre_balsamico",
  "molho_de_cogumelos",
  "molho_chimichurri",
  "molho_pesto",
  "alecrim_desidratado",
  "molho_vinagrete",
  "zaatar",
  "furikake",
  "wasabi",
  "molho_de_beterraba",
  "molho_de_cenoura",
  "molho_de_cheddar",
  "molho_de_almeirao",
  "molho_de_alho_poro_organico",
  "molho_de_rucula_organico",
  "molho_de_cebola_organica",
  "molho_de_salsa",
  "molho_de_espinafre",
  "total_alimentacao_fora_do_domicilio",
  "refeicao",
  "lanche",
  "refrigerante_e_agua_mineral",
  "cafezinho",
  "salada_de_frutas",
  "tapioca_beiju",
  "acai_emulsao",
  "caldos",
  "cha_preparado",
  "cerveja",
  "outras_bebidas_alcoolicas",
  "vinho",
  "doces",
  "biscoito",
  "bala_ou_chiclete",
  "chocolate_e_bombom",
  "sorvete",
  "fruta",
  "iogurte",
  "energetico",
  "isotonico",
  "achocolatado",
  "leite_fermentado",
];

export const columnsNames = [
  // 134
  "2.1.1alimentacao",
  "2.1.1.1alimentacao_no_domicilio",
  "2.1.1.1.1cereais_leguminosas_e_oleaginosas",
  "2.1.1.1.2farinhas_feculas_e_massas",
  "2.1.1.1.3tuberculos_raizes_e_legumes",
  "2.1.1.1.4acucares_e_derivados",
  "2.1.1.1.5hortalicas_e_verduras",
  "2.1.1.1.6frutas",
  "2.1.1.1.7carnes",
  "2.1.1.1.8pescados",
  "2.1.1.1.9carnes_e_peixes_industrializados",
  "2.1.1.1.10aves_e_ovos",
  "2.1.1.1.11leites_e_derivados",
  "2.1.1.1.12panificados",
  "2.1.1.1.13oleos_e_gorduras",
  "2.1.1.1.14bebidas_e_infusoes",
  "2.1.1.1.15enlatados_e_conservas",
  "2.1.1.1.16sal_e_condimentos",
  "2.1.1.1.16.1leite_de_coco",
  "2.1.1.1.16.5atomatado",
  "2.1.1.1.16.10alho",
  "2.1.1.1.16.13sal",
  "2.1.1.1.16.14sal_grosso",
  "2.1.1.1.16.22colorau",
  "2.1.1.1.16.23caldo_de_tucupi",
  "2.1.1.1.16.26fermento",
  "2.1.1.1.16.33maionese",
  "2.1.1.1.16.40vinagre_de_alcool",
  "2.1.1.1.16.41vinagre",
  "2.1.1.1.16.45salsa_desidratada",
  "2.1.1.1.16.46misso",
  "2.1.1.1.16.48caldo_concentrado",
  "2.1.1.1.16.54pimenta_em_po",
  "2.1.1.1.16.55cominho",
  "2.1.1.1.16.56fondor",
  "2.1.1.1.16.57amaciante_de_carne",
  "2.1.1.1.16.59sal_dietetico",
  "2.1.1.1.16.60hortela",
  "2.1.1.1.16.62pimenta-do-reino",
  "2.1.1.1.16.67curry",
  "2.1.1.1.16.69molho_de_tucupi_com_pimenta",
  "2.1.1.1.16.70sal_amoniaco",
  "2.1.1.1.16.71tempero_misto",
  "2.1.1.1.16.72bicarbonato_de_sodio",
  "2.1.1.1.16.73glutamato_monossodico",
  "2.1.1.1.16.75baunilha_em_po",
  "2.1.1.1.16.76canela_em_po",
  "2.1.1.1.16.77cravo",
  "2.1.1.1.16.78paprica",
  "2.1.1.1.16.79noz-moscada",
  "2.1.1.1.16.80mostarda",
  "2.1.1.1.16.81louro",
  "2.1.1.1.16.82acafrao_em_po",
  "2.1.1.1.16.84gengibre",
  "2.1.1.1.16.85alfavaca",
  "2.1.1.1.16.86oregano",
  "2.1.1.1.16.87alcaparra",
  "2.1.1.1.16.88manjerona",
  "2.1.1.1.16.89coentro",
  "2.1.1.1.16.90alho_em_po",
  "2.1.1.1.16.91cebola_em_po",
  "2.1.1.1.16.92cheiro-verde_em_po",
  "2.1.1.1.16.93pimentao_em_po",
  "2.1.1.1.16.94vinagre_de_maca",
  "2.1.1.1.16.95molho_de_soja",
  "2.1.1.1.16.96molho_ingles",
  "2.1.1.1.16.97molho_tartaro",
  "2.1.1.1.16.101molho_branco",
  "2.1.1.1.16.104caldo_de_queijo",
  "2.1.1.1.16.110molho_(nao_especificado)",
  "2.1.1.1.16.115coalho",
  "2.1.1.1.16.116sal_amargo",
  "2.1.1.1.16.117salvia_em_folha",
  "2.1.1.1.16.118erva_doce",
  "2.1.1.1.16.119tomilho_em_folha",
  "2.1.1.1.16.120vinagre_de_arroz",
  "2.1.1.1.16.121vinagre_de_milho",
  "2.1.1.1.16.122gergelim_em_po",
  "2.1.1.1.16.132tempero_de_saladas",
  "2.1.1.1.16.134molho_xadrez",
  "2.1.1.1.16.135molho_de_funghi",
  "2.1.1.1.16.136molho_de_alho",
  "2.1.1.1.16.137molho_de_pimenta",
  "2.1.1.1.16.138molho_madeira",
  "2.1.1.1.16.139molho_para_salada",
  "2.1.1.1.16.140molho_agridoce",
  "2.1.1.1.16.142molho_barbecue",
  "2.1.1.1.16.143molho_de_frango",
  "2.1.1.1.16.144molho_para_carne",
  "2.1.1.1.16.146molho_temperado_parmesao",
  "2.1.1.1.16.148pimenta_calabresa",
  "2.1.1.1.16.149vinagre_de_limao",
  "2.1.1.1.16.150vinagre_balsamico",
  "2.1.1.1.16.154molho_de_cogumelos",
  "2.1.1.1.16.157molho_chimichurri",
  "2.1.1.1.16.158molho_pesto",
  "2.1.1.1.16.160alecrim_desidratado",
  "2.1.1.1.16.161molho_vinagrete",
  "2.1.1.1.16.162zaatar",
  "2.1.1.1.16.163furikake",
  "2.1.1.1.16.164wasabi",
  "2.1.1.1.16.166molho_de_beterraba",
  "2.1.1.1.16.167molho_de_cenoura",
  "2.1.1.1.16.168molho_de_cheddar",
  "2.1.1.1.16.169molho_de_almeirao",
  "2.1.1.1.16.170molho_de_alho_poro_organico",
  "2.1.1.1.16.171molho_de_rucula_organico",
  "2.1.1.1.16.173molho_de_cebola_organica",
  "2.1.1.1.16.174molho_de_salsa",
  "2.1.1.1.16.175molho_de_espinafre",
  "2.1.1.2alimentacao_fora_do_domicilio",
  "2.1.1.2.1.1refeicao",
  "2.1.1.2.1.3lanche",
  "2.1.1.2.1.7refrigerante_e_agua_mineral",
  "2.1.1.2.1.9cafezinho",
  "2.1.1.2.1.26salada_de_frutas",
  "2.1.1.2.1.30tapioca_(beiju)",
  "2.1.1.2.1.31acai_(emulsao)",
  "2.1.1.2.1.32caldos",
  "2.1.1.2.1.33cha_preparado",
  "2.1.1.2.1.48cerveja",
  "2.1.1.2.1.51outras_bebidas_alcoolicas",
  "2.1.1.2.1.52vinho",
  "2.1.1.2.1.61doces",
  "2.1.1.2.1.85biscoito",
  "2.1.1.2.1.86bala_ou_chiclete",
  "2.1.1.2.1.87chocolate_e_bombom",
  "2.1.1.2.1.88sorvete",
  "2.1.1.2.1.89fruta",
  "2.1.1.2.1.90iogurte",
  "2.1.1.2.1.91energetico",
  "2.1.1.2.1.92isotonico",
  "2.1.1.2.1.93achocolatado",
  "2.1.1.2.1.95leite_fermentado",
];

export const i18nText = [ // 134
  "TOTAL_FOOD",
  "TOTAL_FOOD_AT_HOME",
  "CEREAL_LEGUMES_OILSEEDS",
  "FLOUR_STARCH_PASTA",
  "TUBER_ROOTS_LEGUMES",
  "SUGAR_DERIVATIVES",
  "GREENS_VEGETABLES",
  "FRUITS",
  "MEATS",
  "FISH",
  "INDUSTRIALIZED_MEAT_FISH",
  "POULTRY_EGGS",
  "MILK_DERIVATIVES",
  "BAKERY_BREADS",
  "OILS_FATS",
  "DRINKS_INFUSIONS",
  "CANNED_PRESERVES",
  "SPICES",
  "COCONUT_MILK",
  "TOMATO_SAUCES",
  "GARLIC",
  "SALT",
  "COARSE_SALT",
  "FOOD_COLORING",
  "TUCUPI_BROTH",
  "YEAST",
  "MAYONNAISE",
  "ALCOHOL_VINEGAR",
  "COMMON_VINEGAR",
  "DRIED_PARSLEY",
  "MISO",
  "CONCENTRATED_BROTH",
  "PEPPER_POWDER",
  "CUMIN",
  "FONDOR_SPICE",
  "MEAT_TENDERIZER_POWDER",
  "DIET_SALT",
  "MINT",
  "BLACK_PEPPER",
  "CURRY",
  "TUCUPI_SAUCE_WITH_PEPPER",
  "AMMONIA_SALT",
  "MIXED_SEASONING",
  "SODIUM_BICARBONATE",
  "MONOSODIUM_GLUTAMATE",
  "VANILLA_POWDER",
  "CINNAMON_POWDER",
  "CLOVE",
  "PAPRIKA",
  "NUTMEG",
  "MUSTARD",
  "BAY_LEAF",
  "SAFFRON_POWDER",
  "GINGER",
  "ALFAVACA",
  "OREGANO",
  "CAPERS",
  "MARJORAM",
  "CORIANDER",
  "GARLIC_POWDER",
  "ONION_POWDER",
  "SALSA_POWDER",
  "BELL_PEPPER_POWDER",
  "APPLE_VINEGAR",
  "SOY_SAUCE",
  "ENGLISH_SAUCE",
  "TARTAR_SAUCE",
  "WHITE_SAUCE",
  "CHEESE_BROTH",
  "GENERAL_SAUCE",
  "RENNET",
  "BITTER_SALTS",
  "SAGE_LEAF",
  "ANISE",
  "THYMELEAF",
  "RICE_VINEGAR",
  "CORN_VINEGAR",
  "SESAME_POWDER",
  "SALAD_SEASONING",
  "KUNG_PAO_SAUCE",
  "FUNGHI_SAUCE",
  "GARLIC_SAUCE",
  "PEPPER_SAUCE",
  "GRAVY_SAUCE",
  "SALAD_DRESSING",
  "SWEET_AND_SOUR_SAUCE",
  "BARBECUE_SAUCE",
  "CHICKEN_SAUCE",
  "MEAT_SAUCE",
  "GARLIC_PARMESAN_SAUCE",
  "CHILLI_PEPPER",
  "LEMON_VINEGAR",
  "BALSAMIC_VINEGAR",
  "MUSHROOM_SAUCE",
  "CHIMICHURRI_SAUCE",
  "PESTO_SAUCE",
  "DEHYDRATED_ROSEMARY",
  "BRAZILIAN_VINAIGRETTE",
  "ZAATAR",
  "FURIKAKE",
  "WASABI",
  "BEETROOT_SAUCE",
  "CARROT_SAUCE",
  "CHEDDAR_SAUCE",
  "CHICORY_SAUCE",
  "ORGANIC_LEEK_SAUCE",
  "ORGANIC_ARUGULA_SAUCE",
  "ORGANIC_ONION_SAUCE",
  "PARSLEY_SAUCE",
  "SPINACH_SAUCE",
  "TOTAL_FOOD_OUTSIDE_HOME",
  "MEAL",
  "SNACK",
  "SOFT_DRINK_AND_WATER",
  "COFFEE",
  "FRUIT_SALAD",
  "TAPIOCA",
  "ACAI",
  "BROTHS_SOUPS",
  "TEA",
  "BEER",
  "GENERAL_ALCOHOLIC_BEVERAGE",
  "WINE",
  "CANDIES",
  "COOKIE",
  "BULLET_GUM",
  "CHOCOLATE_SUGARPLUM",
  "ICECREAM",
  "FRUIT",
  "YOGURT",
  "ENERGY_DRINK",
  "SPORTS_DRINK",
  "CHOCOLATE_MILK",
  "FERMENTED_MILK",
];

export const combineArraysToObject = (keys, columns) => {
  const result = {};

  keys.forEach((key, index) => {
    result[key] = columns[index];
  });

  return result;
};

// const result = combineArraysToObject(keys, columns);
// console.log(result);

// const finalResult = buildResultArray(keys);
// console.log(JSON.stringify(finalResult));

export const formatted = [
  `COALESCE(toFloat64(SUM(ts."{columns.total_alimentacao}"))) "{columns.total_alimentacao}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.total_alimentacao_no_domicilio}"))) "{columns.total_alimentacao_no_domicilio}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.cereais_leguminosas_e_oleaginosas}"))) "{columns.cereais_leguminosas_e_oleaginosas}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.farinhas_feculas_e_massas}"))) "{columns.farinhas_feculas_e_massas}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.tuberculos_raizes_e_legumes}"))) "{columns.tuberculos_raizes_e_legumes}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.acucares_e_derivados}"))) "{columns.acucares_e_derivados}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.hortalicas_e_verduras}"))) "{columns.hortalicas_e_verduras}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.frutas}"))) "{columns.frutas}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.carnes}"))) "{columns.carnes}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.pescados}"))) "{columns.pescados}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.carnes_e_peixes_industrializados}"))) "{columns.carnes_e_peixes_industrializados}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.aves_e_ovos}"))) "{columns.aves_e_ovos}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.leites_e_derivados}"))) "{columns.leites_e_derivados}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.panificados}"))) "{columns.panificados}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.oleos_e_gorduras}"))) "{columns.oleos_e_gorduras}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.bebidas_e_infusoes}"))) "{columns.bebidas_e_infusoes}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.enlatados_e_conservas}"))) "{columns.enlatados_e_conservas}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.sal_e_condimentos}"))) "{columns.sal_e_condimentos}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.leite_de_coco}"))) "{columns.leite_de_coco}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.atomatado}"))) "{columns.atomatado}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.alho}"))) "{columns.alho}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.sal}"))) "{columns.sal}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.sal_grosso}"))) "{columns.sal_grosso}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.colorau}"))) "{columns.colorau}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.caldo_de_tucupi}"))) "{columns.caldo_de_tucupi}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.fermento}"))) "{columns.fermento}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.maionese}"))) "{columns.maionese}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.vinagre_de_alcool}"))) "{columns.vinagre_de_alcool}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.vinagre}"))) "{columns.vinagre}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.salsa_desidratada}"))) "{columns.salsa_desidratada}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.misso}"))) "{columns.misso}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.caldo_concentrado}"))) "{columns.caldo_concentrado}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.pimenta_em_po}"))) "{columns.pimenta_em_po}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.cominho}"))) "{columns.cominho}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.fondor}"))) "{columns.fondor}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.amaciante_de_carne}"))) "{columns.amaciante_de_carne}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.sal_dietetico}"))) "{columns.sal_dietetico}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.hortela}"))) "{columns.hortela}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.pimenta_do_reino}"))) "{columns.pimenta_do_reino}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.curry}"))) "{columns.curry}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_tucupi_com_pimenta}"))) "{columns.molho_de_tucupi_com_pimenta}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.sal_amoniaco}"))) "{columns.sal_amoniaco}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.tempero_misto}"))) "{columns.tempero_misto}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.bicarbonato_de_sodio}"))) "{columns.bicarbonato_de_sodio}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.glutamato_monossodico}"))) "{columns.glutamato_monossodico}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.baunilha_em_po}"))) "{columns.baunilha_em_po}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.canela_em_po}"))) "{columns.canela_em_po}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.cravo}"))) "{columns.cravo}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.paprica}"))) "{columns.paprica}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.noz_moscada}"))) "{columns.noz_moscada}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.mostarda}"))) "{columns.mostarda}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.louro}"))) "{columns.louro}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.acafrao_em_po}"))) "{columns.acafrao_em_po}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.gengibre}"))) "{columns.gengibre}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.alfavaca}"))) "{columns.alfavaca}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.oregano}"))) "{columns.oregano}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.alcaparra}"))) "{columns.alcaparra}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.manjerona}"))) "{columns.manjerona}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.coentro}"))) "{columns.coentro}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.alho_em_po}"))) "{columns.alho_em_po}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.cebola_em_po}"))) "{columns.cebola_em_po}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.cheiro_verde_em_po}"))) "{columns.cheiro_verde_em_po}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.pimentao_em_po}"))) "{columns.pimentao_em_po}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.vinagre_de_maca}"))) "{columns.vinagre_de_maca}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_soja}"))) "{columns.molho_de_soja}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_ingles}"))) "{columns.molho_ingles}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_tartaro}"))) "{columns.molho_tartaro}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_branco}"))) "{columns.molho_branco}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.caldo_de_queijo}"))) "{columns.caldo_de_queijo}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_nao_especificado}"))) "{columns.molho_nao_especificado}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.coalho}"))) "{columns.coalho}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.sal_amargo}"))) "{columns.sal_amargo}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.salvia_em_folha}"))) "{columns.salvia_em_folha}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.erva_doce}"))) "{columns.erva_doce}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.tomilho_em_folha}"))) "{columns.tomilho_em_folha}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.vinagre_de_arroz}"))) "{columns.vinagre_de_arroz}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.vinagre_de_milho}"))) "{columns.vinagre_de_milho}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.gergelim_em_po}"))) "{columns.gergelim_em_po}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.tempero_de_saladas}"))) "{columns.tempero_de_saladas}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_xadrez}"))) "{columns.molho_xadrez}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_funghi}"))) "{columns.molho_de_funghi}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_alho}"))) "{columns.molho_de_alho}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_pimenta}"))) "{columns.molho_de_pimenta}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_madeira}"))) "{columns.molho_madeira}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_para_salada}"))) "{columns.molho_para_salada}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_agridoce}"))) "{columns.molho_agridoce}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_barbecue}"))) "{columns.molho_barbecue}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_frango}"))) "{columns.molho_de_frango}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_para_carne}"))) "{columns.molho_para_carne}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_temperado_parmesao}"))) "{columns.molho_temperado_parmesao}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.pimenta_calabresa}"))) "{columns.pimenta_calabresa}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.vinagre_de_limao}"))) "{columns.vinagre_de_limao}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.vinagre_balsamico}"))) "{columns.vinagre_balsamico}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_cogumelos}"))) "{columns.molho_de_cogumelos}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_chimichurri}"))) "{columns.molho_chimichurri}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_pesto}"))) "{columns.molho_pesto}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.alecrim_desidratado}"))) "{columns.alecrim_desidratado}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_vinagrete}"))) "{columns.molho_vinagrete}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.zaatar}"))) "{columns.zaatar}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.furikake}"))) "{columns.furikake}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.wasabi}"))) "{columns.wasabi}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_beterraba}"))) "{columns.molho_de_beterraba}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_cenoura}"))) "{columns.molho_de_cenoura}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_cheddar}"))) "{columns.molho_de_cheddar}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_almeirao}"))) "{columns.molho_de_almeirao}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_alho_poro_organico}"))) "{columns.molho_de_alho_poro_organico}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_rucula_organico}"))) "{columns.molho_de_rucula_organico}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_cebola_organica}"))) "{columns.molho_de_cebola_organica}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_salsa}"))) "{columns.molho_de_salsa}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.molho_de_espinafre}"))) "{columns.molho_de_espinafre}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.total_alimentacao_fora_do_domicilio}"))) "{columns.total_alimentacao_fora_do_domicilio}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.refeicao}"))) "{columns.refeicao}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.lanche}"))) "{columns.lanche}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.refrigerante_e_agua_mineral}"))) "{columns.refrigerante_e_agua_mineral}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.cafezinho}"))) "{columns.cafezinho}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.salada_de_frutas}"))) "{columns.salada_de_frutas}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.tapioca_beiju}"))) "{columns.tapioca_beiju}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.acai_emulsao}"))) "{columns.acai_emulsao}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.caldos}"))) "{columns.caldos}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.cha_preparado}"))) "{columns.cha_preparado}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.cerveja}"))) "{columns.cerveja}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.outras_bebidas_alcoolicas}"))) "{columns.outras_bebidas_alcoolicas}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.vinho}"))) "{columns.vinho}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.doces}"))) "{columns.doces}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.biscoito}"))) "{columns.biscoito}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.bala_ou_chiclete}"))) "{columns.bala_ou_chiclete}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.chocolate_e_bombom}"))) "{columns.chocolate_e_bombom}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.sorvete}"))) "{columns.sorvete}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.fruta}"))) "{columns.fruta}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.iogurte}"))) "{columns.iogurte}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.energetico}"))) "{columns.energetico}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.isotonico}"))) "{columns.isotonico}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.achocolatado}"))) "{columns.achocolatado}"`,
  `COALESCE(toFloat64(SUM(ts."{columns.leite_fermentado}"))) "{columns.leite_fermentado}"`,
];

// console.log("combineArraysToObject \n", combineArraysToObject(keys, formatted));

// export const finalObject = {
//   total_alimentacao: `COALESCE(toFloat64(SUM(ts."${columns.total_alimentacao}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.total_alimentacao}"`,
//   total_alimentacao_no_domicilio: `COALESCE(toFloat64(SUM(ts."${columns.total_alimentacao_no_domicilio}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.total_alimentacao_no_domicilio}"`,
//   cereais_leguminosas_e_oleaginosas: `COALESCE(toFloat64(SUM(ts."${columns.cereais_leguminosas_e_oleaginosas}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.cereais_leguminosas_e_oleaginosas}"`,
//   farinhas_feculas_e_massas: `COALESCE(toFloat64(SUM(ts."${columns.farinhas_feculas_e_massas}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.farinhas_feculas_e_massas}"`,
//   tuberculos_raizes_e_legumes: `COALESCE(toFloat64(SUM(ts."${columns.tuberculos_raizes_e_legumes}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.tuberculos_raizes_e_legumes}"`,
//   acucares_e_derivados: `COALESCE(toFloat64(SUM(ts."${columns.acucares_e_derivados}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.acucares_e_derivados}"`,
//   hortalicas_e_verduras: `COALESCE(toFloat64(SUM(ts."${columns.hortalicas_e_verduras}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.hortalicas_e_verduras}"`,
//   frutas: `COALESCE(toFloat64(SUM(ts."${columns.frutas}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.frutas}"`,
//   carnes: `COALESCE(toFloat64(SUM(ts."${columns.carnes}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.carnes}"`,
//   pescados: `COALESCE(toFloat64(SUM(ts."${columns.pescados}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.pescados}"`,
//   carnes_e_peixes_industrializados: `COALESCE(toFloat64(SUM(ts."${columns.carnes_e_peixes_industrializados}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.carnes_e_peixes_industrializados}"`,
//   aves_e_ovos: `COALESCE(toFloat64(SUM(ts."${columns.aves_e_ovos}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.aves_e_ovos}"`,
//   leites_e_derivados: `COALESCE(toFloat64(SUM(ts."${columns.leites_e_derivados}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.leites_e_derivados}"`,
//   panificados: `COALESCE(toFloat64(SUM(ts."${columns.panificados}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.panificados}"`,
//   oleos_e_gorduras: `COALESCE(toFloat64(SUM(ts."${columns.oleos_e_gorduras}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.oleos_e_gorduras}"`,
//   bebidas_e_infusoes: `COALESCE(toFloat64(SUM(ts."${columns.bebidas_e_infusoes}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.bebidas_e_infusoes}"`,
//   enlatados_e_conservas: `COALESCE(toFloat64(SUM(ts."${columns.enlatados_e_conservas}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.enlatados_e_conservas}"`,
//   sal_e_condimentos: `COALESCE(toFloat64(SUM(ts."${columns.sal_e_condimentos}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.sal_e_condimentos}"`,
//   leite_de_coco: `COALESCE(toFloat64(SUM(ts."${columns.leite_de_coco}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.leite_de_coco}"`,
//   atomatado: `COALESCE(toFloat64(SUM(ts."${columns.atomatado}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.atomatado}"`,
//   alho: `COALESCE(toFloat64(SUM(ts."${columns.alho}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.alho}"`,
//   sal: `COALESCE(toFloat64(SUM(ts."${columns.sal}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.sal}"`,
//   sal_grosso: `COALESCE(toFloat64(SUM(ts."${columns.sal_grosso}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.sal_grosso}"`,
//   colorau: `COALESCE(toFloat64(SUM(ts."${columns.colorau}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.colorau}"`,
//   caldo_de_tucupi: `COALESCE(toFloat64(SUM(ts."${columns.caldo_de_tucupi}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.caldo_de_tucupi}"`,
//   fermento: `COALESCE(toFloat64(SUM(ts."${columns.fermento}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.fermento}"`,
//   maionese: `COALESCE(toFloat64(SUM(ts."${columns.maionese}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.maionese}"`,
//   vinagre_de_alcool: `COALESCE(toFloat64(SUM(ts."${columns.vinagre_de_alcool}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.vinagre_de_alcool}"`,
//   vinagre: `COALESCE(toFloat64(SUM(ts."${columns.vinagre}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.vinagre}"`,
//   salsa_desidratada: `COALESCE(toFloat64(SUM(ts."${columns.salsa_desidratada}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.salsa_desidratada}"`,
//   misso: `COALESCE(toFloat64(SUM(ts."${columns.misso}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.misso}"`,
//   caldo_concentrado: `COALESCE(toFloat64(SUM(ts."${columns.caldo_concentrado}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.caldo_concentrado}"`,
//   pimenta_em_po: `COALESCE(toFloat64(SUM(ts."${columns.pimenta_em_po}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.pimenta_em_po}"`,
//   cominho: `COALESCE(toFloat64(SUM(ts."${columns.cominho}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.cominho}"`,
//   fondor: `COALESCE(toFloat64(SUM(ts."${columns.fondor}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.fondor}"`,
//   amaciante_de_carne: `COALESCE(toFloat64(SUM(ts."${columns.amaciante_de_carne}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.amaciante_de_carne}"`,
//   sal_dietetico: `COALESCE(toFloat64(SUM(ts."${columns.sal_dietetico}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.sal_dietetico}"`,
//   hortela: `COALESCE(toFloat64(SUM(ts."${columns.hortela}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.hortela}"`,
//   pimenta_do_reino: `COALESCE(toFloat64(SUM(ts."${columns.pimenta_do_reino}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.pimenta_do_reino}"`,
//   curry: `COALESCE(toFloat64(SUM(ts."${columns.curry}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.curry}"`,
//   molho_de_tucupi_com_pimenta: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_tucupi_com_pimenta}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_tucupi_com_pimenta}"`,
//   sal_amoniaco: `COALESCE(toFloat64(SUM(ts."${columns.sal_amoniaco}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.sal_amoniaco}"`,
//   tempero_misto: `COALESCE(toFloat64(SUM(ts."${columns.tempero_misto}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.tempero_misto}"`,
//   bicarbonato_de_sodio: `COALESCE(toFloat64(SUM(ts."${columns.bicarbonato_de_sodio}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.bicarbonato_de_sodio}"`,
//   glutamato_monossodico: `COALESCE(toFloat64(SUM(ts."${columns.glutamato_monossodico}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.glutamato_monossodico}"`,
//   baunilha_em_po: `COALESCE(toFloat64(SUM(ts."${columns.baunilha_em_po}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.baunilha_em_po}"`,
//   canela_em_po: `COALESCE(toFloat64(SUM(ts."${columns.canela_em_po}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.canela_em_po}"`,
//   cravo: `COALESCE(toFloat64(SUM(ts."${columns.cravo}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.cravo}"`,
//   paprica: `COALESCE(toFloat64(SUM(ts."${columns.paprica}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.paprica}"`,
//   noz_moscada: `COALESCE(toFloat64(SUM(ts."${columns.noz_moscada}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.noz_moscada}"`,
//   mostarda: `COALESCE(toFloat64(SUM(ts."${columns.mostarda}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.mostarda}"`,
//   louro: `COALESCE(toFloat64(SUM(ts."${columns.louro}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.louro}"`,
//   acafrao_em_po: `COALESCE(toFloat64(SUM(ts."${columns.acafrao_em_po}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.acafrao_em_po}"`,
//   gengibre: `COALESCE(toFloat64(SUM(ts."${columns.gengibre}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.gengibre}"`,
//   alfavaca: `COALESCE(toFloat64(SUM(ts."${columns.alfavaca}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.alfavaca}"`,
//   oregano: `COALESCE(toFloat64(SUM(ts."${columns.oregano}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.oregano}"`,
//   alcaparra: `COALESCE(toFloat64(SUM(ts."${columns.alcaparra}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.alcaparra}"`,
//   manjerona: `COALESCE(toFloat64(SUM(ts."${columns.manjerona}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.manjerona}"`,
//   coentro: `COALESCE(toFloat64(SUM(ts."${columns.coentro}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.coentro}"`,
//   alho_em_po: `COALESCE(toFloat64(SUM(ts."${columns.alho_em_po}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.alho_em_po}"`,
//   cebola_em_po: `COALESCE(toFloat64(SUM(ts."${columns.cebola_em_po}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.cebola_em_po}"`,
//   cheiro_verde_em_po: `COALESCE(toFloat64(SUM(ts."${columns.cheiro_verde_em_po}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.cheiro_verde_em_po}"`,
//   pimentao_em_po: `COALESCE(toFloat64(SUM(ts."${columns.pimentao_em_po}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.pimentao_em_po}"`,
//   vinagre_de_maca: `COALESCE(toFloat64(SUM(ts."${columns.vinagre_de_maca}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.vinagre_de_maca}"`,
//   molho_de_soja: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_soja}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_soja}"`,
//   molho_ingles: `COALESCE(toFloat64(SUM(ts."${columns.molho_ingles}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_ingles}"`,
//   molho_tartaro: `COALESCE(toFloat64(SUM(ts."${columns.molho_tartaro}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_tartaro}"`,
//   molho_branco: `COALESCE(toFloat64(SUM(ts."${columns.molho_branco}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_branco}"`,
//   caldo_de_queijo: `COALESCE(toFloat64(SUM(ts."${columns.caldo_de_queijo}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.caldo_de_queijo}"`,
//   molho_nao_especificado: `COALESCE(toFloat64(SUM(ts."${columns.molho_nao_especificado}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_nao_especificado}"`,
//   coalho: `COALESCE(toFloat64(SUM(ts."${columns.coalho}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.coalho}"`,
//   sal_amargo: `COALESCE(toFloat64(SUM(ts."${columns.sal_amargo}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.sal_amargo}"`,
//   salvia_em_folha: `COALESCE(toFloat64(SUM(ts."${columns.salvia_em_folha}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.salvia_em_folha}"`,
//   erva_doce: `COALESCE(toFloat64(SUM(ts."${columns.erva_doce}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.erva_doce}"`,
//   tomilho_em_folha: `COALESCE(toFloat64(SUM(ts."${columns.tomilho_em_folha}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.tomilho_em_folha}"`,
//   vinagre_de_arroz: `COALESCE(toFloat64(SUM(ts."${columns.vinagre_de_arroz}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.vinagre_de_arroz}"`,
//   vinagre_de_milho: `COALESCE(toFloat64(SUM(ts."${columns.vinagre_de_milho}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.vinagre_de_milho}"`,
//   gergelim_em_po: `COALESCE(toFloat64(SUM(ts."${columns.gergelim_em_po}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.gergelim_em_po}"`,
//   tempero_de_saladas: `COALESCE(toFloat64(SUM(ts."${columns.tempero_de_saladas}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.tempero_de_saladas}"`,
//   molho_xadrez: `COALESCE(toFloat64(SUM(ts."${columns.molho_xadrez}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_xadrez}"`,
//   molho_de_funghi: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_funghi}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_funghi}"`,
//   molho_de_alho: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_alho}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_alho}"`,
//   molho_de_pimenta: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_pimenta}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_pimenta}"`,
//   molho_madeira: `COALESCE(toFloat64(SUM(ts."${columns.molho_madeira}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_madeira}"`,
//   molho_para_salada: `COALESCE(toFloat64(SUM(ts."${columns.molho_para_salada}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_para_salada}"`,
//   molho_agridoce: `COALESCE(toFloat64(SUM(ts."${columns.molho_agridoce}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_agridoce}"`,
//   molho_barbecue: `COALESCE(toFloat64(SUM(ts."${columns.molho_barbecue}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_barbecue}"`,
//   molho_de_frango: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_frango}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_frango}"`,
//   molho_para_carne: `COALESCE(toFloat64(SUM(ts."${columns.molho_para_carne}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_para_carne}"`,
//   molho_temperado_parmesao: `COALESCE(toFloat64(SUM(ts."${columns.molho_temperado_parmesao}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_temperado_parmesao}"`,
//   pimenta_calabresa: `COALESCE(toFloat64(SUM(ts."${columns.pimenta_calabresa}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.pimenta_calabresa}"`,
//   vinagre_de_limao: `COALESCE(toFloat64(SUM(ts."${columns.vinagre_de_limao}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.vinagre_de_limao}"`,
//   vinagre_balsamico: `COALESCE(toFloat64(SUM(ts."${columns.vinagre_balsamico}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.vinagre_balsamico}"`,
//   molho_de_cogumelos: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_cogumelos}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_cogumelos}"`,
//   molho_chimichurri: `COALESCE(toFloat64(SUM(ts."${columns.molho_chimichurri}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_chimichurri}"`,
//   molho_pesto: `COALESCE(toFloat64(SUM(ts."${columns.molho_pesto}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_pesto}"`,
//   alecrim_desidratado: `COALESCE(toFloat64(SUM(ts."${columns.alecrim_desidratado}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.alecrim_desidratado}"`,
//   molho_vinagrete: `COALESCE(toFloat64(SUM(ts."${columns.molho_vinagrete}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_vinagrete}"`,
//   zaatar: `COALESCE(toFloat64(SUM(ts."${columns.zaatar}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.zaatar}"`,
//   furikake: `COALESCE(toFloat64(SUM(ts."${columns.furikake}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.furikake}"`,
//   wasabi: `COALESCE(toFloat64(SUM(ts."${columns.wasabi}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.wasabi}"`,
//   molho_de_beterraba: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_beterraba}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_beterraba}"`,
//   molho_de_cenoura: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_cenoura}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_cenoura}"`,
//   molho_de_cheddar: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_cheddar}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_cheddar}"`,
//   molho_de_almeirao: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_almeirao}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_almeirao}"`,
//   molho_de_alho_poro_organico: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_alho_poro_organico}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_alho_poro_organico}"`,
//   molho_de_rucula_organico: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_rucula_organico}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_rucula_organico}"`,
//   molho_de_cebola_organica: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_cebola_organica}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_cebola_organica}"`,
//   molho_de_salsa: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_salsa}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_salsa}"`,
//   molho_de_espinafre: `COALESCE(toFloat64(SUM(ts."${columns.molho_de_espinafre}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.molho_de_espinafre}"`,
//   total_alimentacao_fora_do_domicilio: `COALESCE(toFloat64(SUM(ts."${columns.total_alimentacao_fora_do_domicilio}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.total_alimentacao_fora_do_domicilio}"`,
//   refeicao: `COALESCE(toFloat64(SUM(ts."${columns.refeicao}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.refeicao}"`,
//   lanche: `COALESCE(toFloat64(SUM(ts."${columns.lanche}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.lanche}"`,
//   refrigerante_e_agua_mineral: `COALESCE(toFloat64(SUM(ts."${columns.refrigerante_e_agua_mineral}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.refrigerante_e_agua_mineral}"`,
//   cafezinho: `COALESCE(toFloat64(SUM(ts."${columns.cafezinho}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.cafezinho}"`,
//   salada_de_frutas: `COALESCE(toFloat64(SUM(ts."${columns.salada_de_frutas}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.salada_de_frutas}"`,
//   tapioca_beiju: `COALESCE(toFloat64(SUM(ts."${columns.tapioca_beiju}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.tapioca_beiju}"`,
//   acai_emulsao: `COALESCE(toFloat64(SUM(ts."${columns.acai_emulsao}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.acai_emulsao}"`,
//   caldos: `COALESCE(toFloat64(SUM(ts."${columns.caldos}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.caldos}"`,
//   cha_preparado: `COALESCE(toFloat64(SUM(ts."${columns.cha_preparado}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.cha_preparado}"`,
//   cerveja: `COALESCE(toFloat64(SUM(ts."${columns.cerveja}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.cerveja}"`,
//   outras_bebidas_alcoolicas: `COALESCE(toFloat64(SUM(ts."${columns.outras_bebidas_alcoolicas}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.outras_bebidas_alcoolicas}"`,
//   vinho: `COALESCE(toFloat64(SUM(ts."${columns.vinho}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.vinho}"`,
//   doces: `COALESCE(toFloat64(SUM(ts."${columns.doces}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.doces}"`,
//   biscoito: `COALESCE(toFloat64(SUM(ts."${columns.biscoito}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.biscoito}"`,
//   bala_ou_chiclete: `COALESCE(toFloat64(SUM(ts."${columns.bala_ou_chiclete}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.bala_ou_chiclete}"`,
//   chocolate_e_bombom: `COALESCE(toFloat64(SUM(ts."${columns.chocolate_e_bombom}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.chocolate_e_bombom}"`,
//   sorvete: `COALESCE(toFloat64(SUM(ts."${columns.sorvete}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.sorvete}"`,
//   fruta: `COALESCE(toFloat64(SUM(ts."${columns.fruta}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.fruta}"`,
//   iogurte: `COALESCE(toFloat64(SUM(ts."${columns.iogurte}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.iogurte}"`,
//   energetico: `COALESCE(toFloat64(SUM(ts."${columns.energetico}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.energetico}"`,
//   isotonico: `COALESCE(toFloat64(SUM(ts."${columns.isotonico}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.isotonico}"`,
//   achocolatado: `COALESCE(toFloat64(SUM(ts."${columns.achocolatado}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.achocolatado}"`,
//   leite_fermentado: `COALESCE(toFloat64(SUM(ts."${columns.leite_fermentado}")) / toFloat64(SUM(${columns.domicilios_perm})), 0) "${columns.leite_fermentado}"`,
// };

export const columnNameObjectFormat = {
  alimentacao: "2.1.1alimentacao",
  total_alimentacao: "2.1.1alimentacao",
  total_alimentacao_no_domicilio: "2.1.1.1alimentacao_no_domicilio",
  cereais_leguminosas_e_oleaginosas:
    "2.1.1.1.1cereais_leguminosas_e_oleaginosas",
  farinhas_feculas_e_massas: "2.1.1.1.2farinhas_feculas_e_massas",
  tuberculos_raizes_e_legumes: "2.1.1.1.3tuberculos_raizes_e_legumes",
  acucares_e_derivados: "2.1.1.1.4acucares_e_derivados",
  hortalicas_e_verduras: "2.1.1.1.5hortalicas_e_verduras",
  frutas: "2.1.1.1.6frutas",
  carnes: "2.1.1.1.7carnes",
  pescados: "2.1.1.1.8pescados",
  carnes_e_peixes_industrializados: "2.1.1.1.9carnes_e_peixes_industrializados",
  aves_e_ovos: "2.1.1.1.10aves_e_ovos",
  leites_e_derivados: "2.1.1.1.11leites_e_derivados",
  panificados: "2.1.1.1.12panificados",
  oleos_e_gorduras: "2.1.1.1.13oleos_e_gorduras",
  bebidas_e_infusoes: "2.1.1.1.14bebidas_e_infusoes",
  enlatados_e_conservas: "2.1.1.1.15enlatados_e_conservas",
  sal_e_condimentos: "2.1.1.1.16sal_e_condimentos",
  leite_de_coco: "2.1.1.1.16.1leite_de_coco",
  atomatado: "2.1.1.1.16.5atomatado",
  alho: "2.1.1.1.16.10alho",
  sal: "2.1.1.1.16.13sal",
  sal_grosso: "2.1.1.1.16.14sal_grosso",
  colorau: "2.1.1.1.16.22colorau",
  caldo_de_tucupi: "2.1.1.1.16.23caldo_de_tucupi",
  fermento: "2.1.1.1.16.26fermento",
  maionese: "2.1.1.1.16.33maionese",
  vinagre_de_alcool: "2.1.1.1.16.40vinagre_de_alcool",
  vinagre: "2.1.1.1.16.41vinagre",
  salsa_desidratada: "2.1.1.1.16.45salsa_desidratada",
  misso: "2.1.1.1.16.46misso",
  caldo_concentrado: "2.1.1.1.16.48caldo_concentrado",
  pimenta_em_po: "2.1.1.1.16.54pimenta_em_po",
  cominho: "2.1.1.1.16.55cominho",
  fondor: "2.1.1.1.16.56fondor",
  amaciante_de_carne: "2.1.1.1.16.57amaciante_de_carne",
  sal_dietetico: "2.1.1.1.16.59sal_dietetico",
  hortela: "2.1.1.1.16.60hortela",
  pimenta_do_reino: "2.1.1.1.16.62pimenta-do-reino",
  curry: "2.1.1.1.16.67curry",
  molho_de_tucupi_com_pimenta: "2.1.1.1.16.69molho_de_tucupi_com_pimenta",
  sal_amoniaco: "2.1.1.1.16.70sal_amoniaco",
  tempero_misto: "2.1.1.1.16.71tempero_misto",
  bicarbonato_de_sodio: "2.1.1.1.16.72bicarbonato_de_sodio",
  glutamato_monossodico: "2.1.1.1.16.73glutamato_monossodico",
  baunilha_em_po: "2.1.1.1.16.75baunilha_em_po",
  canela_em_po: "2.1.1.1.16.76canela_em_po",
  cravo: "2.1.1.1.16.77cravo",
  paprica: "2.1.1.1.16.78paprica",
  noz_moscada: "2.1.1.1.16.79noz-moscada",
  mostarda: "2.1.1.1.16.80mostarda",
  louro: "2.1.1.1.16.81louro",
  acafrao_em_po: "2.1.1.1.16.82acafrao_em_po",
  gengibre: "2.1.1.1.16.84gengibre",
  alfavaca: "2.1.1.1.16.85alfavaca",
  oregano: "2.1.1.1.16.86oregano",
  alcaparra: "2.1.1.1.16.87alcaparra",
  manjerona: "2.1.1.1.16.88manjerona",
  coentro: "2.1.1.1.16.89coentro",
  alho_em_po: "2.1.1.1.16.90alho_em_po",
  cebola_em_po: "2.1.1.1.16.91cebola_em_po",
  cheiro_verde_em_po: "2.1.1.1.16.92cheiro-verde_em_po",
  pimentao_em_po: "2.1.1.1.16.93pimentao_em_po",
  vinagre_de_maca: "2.1.1.1.16.94vinagre_de_maca",
  molho_de_soja: "2.1.1.1.16.95molho_de_soja",
  molho_ingles: "2.1.1.1.16.96molho_ingles",
  molho_tartaro: "2.1.1.1.16.97molho_tartaro",
  molho_branco: "2.1.1.1.16.101molho_branco",
  caldo_de_queijo: "2.1.1.1.16.104caldo_de_queijo",
  molho_nao_especificado: "2.1.1.1.16.110molho_(nao_especificado)",
  coalho: "2.1.1.1.16.115coalho",
  sal_amargo: "2.1.1.1.16.116sal_amargo",
  salvia_em_folha: "2.1.1.1.16.117salvia_em_folha",
  erva_doce: "2.1.1.1.16.118erva_doce",
  tomilho_em_folha: "2.1.1.1.16.119tomilho_em_folha",
  vinagre_de_arroz: "2.1.1.1.16.120vinagre_de_arroz",
  vinagre_de_milho: "2.1.1.1.16.121vinagre_de_milho",
  gergelim_em_po: "2.1.1.1.16.122gergelim_em_po",
  tempero_de_saladas: "2.1.1.1.16.132tempero_de_saladas",
  molho_xadrez: "2.1.1.1.16.134molho_xadrez",
  molho_de_funghi: "2.1.1.1.16.135molho_de_funghi",
  molho_de_alho: "2.1.1.1.16.136molho_de_alho",
  molho_de_pimenta: "2.1.1.1.16.137molho_de_pimenta",
  molho_madeira: "2.1.1.1.16.138molho_madeira",
  molho_para_salada: "2.1.1.1.16.139molho_para_salada",
  molho_agridoce: "2.1.1.1.16.140molho_agridoce",
  molho_barbecue: "2.1.1.1.16.142molho_barbecue",
  molho_de_frango: "2.1.1.1.16.143molho_de_frango",
  molho_para_carne: "2.1.1.1.16.144molho_para_carne",
  molho_temperado_parmesao: "2.1.1.1.16.146molho_temperado_parmesao",
  pimenta_calabresa: "2.1.1.1.16.148pimenta_calabresa",
  vinagre_de_limao: "2.1.1.1.16.149vinagre_de_limao",
  vinagre_balsamico: "2.1.1.1.16.150vinagre_balsamico",
  molho_de_cogumelos: "2.1.1.1.16.154molho_de_cogumelos",
  molho_chimichurri: "2.1.1.1.16.157molho_chimichurri",
  molho_pesto: "2.1.1.1.16.158molho_pesto",
  alecrim_desidratado: "2.1.1.1.16.160alecrim_desidratado",
  molho_vinagrete: "2.1.1.1.16.161molho_vinagrete",
  zaatar: "2.1.1.1.16.162zaatar",
  furikake: "2.1.1.1.16.163furikake",
  wasabi: "2.1.1.1.16.164wasabi",
  molho_de_beterraba: "2.1.1.1.16.166molho_de_beterraba",
  molho_de_cenoura: "2.1.1.1.16.167molho_de_cenoura",
  molho_de_cheddar: "2.1.1.1.16.168molho_de_cheddar",
  molho_de_almeirao: "2.1.1.1.16.169molho_de_almeirao",
  molho_de_alho_poro_organico: "2.1.1.1.16.170molho_de_alho_poro_organico",
  molho_de_rucula_organico: "2.1.1.1.16.171molho_de_rucula_organico",
  molho_de_cebola_organica: "2.1.1.1.16.173molho_de_cebola_organica",
  molho_de_salsa: "2.1.1.1.16.174molho_de_salsa",
  molho_de_espinafre: "2.1.1.1.16.175molho_de_espinafre",
  total_alimentacao_fora_do_domicilio: "2.1.1.2alimentacao_fora_do_domicilio",
  refeicao: "2.1.1.2.1.1refeicao",
  lanche: "2.1.1.2.1.3lanche",
  refrigerante_e_agua_mineral: "2.1.1.2.1.7refrigerante_e_agua_mineral",
  cafezinho: "2.1.1.2.1.9cafezinho",
  salada_de_frutas: "2.1.1.2.1.26salada_de_frutas",
  tapioca_beiju: "2.1.1.2.1.30tapioca_(beiju)",
  acai_emulsao: "2.1.1.2.1.31acai_(emulsao)",
  caldos: "2.1.1.2.1.32caldos",
  cha_preparado: "2.1.1.2.1.33cha_preparado",
  cerveja: "2.1.1.2.1.48cerveja",
  outras_bebidas_alcoolicas: "2.1.1.2.1.51outras_bebidas_alcoolicas",
  vinho: "2.1.1.2.1.52vinho",
  doces: "2.1.1.2.1.61doces",
  biscoito: "2.1.1.2.1.85biscoito",
  bala_ou_chiclete: "2.1.1.2.1.86bala_ou_chiclete",
  chocolate_e_bombom: "2.1.1.2.1.87chocolate_e_bombom",
  sorvete: "2.1.1.2.1.88sorvete",
  fruta: "2.1.1.2.1.89fruta",
  iogurte: "2.1.1.2.1.90iogurte",
  energetico: "2.1.1.2.1.91energetico",
  isotonico: "2.1.1.2.1.92isotonico",
  achocolatado: "2.1.1.2.1.93achocolatado",
  leite_fermentado: "2.1.1.2.1.95leite_fermentado",
};



// const categoriasConsumoComidas = [
//   COALESCE(round(toFloat64(SUM("${columns.total_alimentacao}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.total_alimentacao}",
//   COALESCE(round(toFloat64(SUM("${columns.total_alimentacao_no_domicilio}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.total_alimentacao_no_domicilio}",
//   COALESCE(round(toFloat64(SUM("${columns.cereais_leguminosas_e_oleaginosas}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.cereais_leguminosas_e_oleaginosas}",
//   COALESCE(round(toFloat64(SUM("${columns.farinhas_feculas_e_massas}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.farinhas_feculas_e_massas}",
//   COALESCE(round(toFloat64(SUM("${columns.tuberculos_raizes_e_legumes}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.tuberculos_raizes_e_legumes}",
//   COALESCE(round(toFloat64(SUM("${columns.acucares_e_derivados}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.acucares_e_derivados}",
//   COALESCE(round(toFloat64(SUM("${columns.hortalicas_e_verduras}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.hortalicas_e_verduras}",
//   COALESCE(round(toFloat64(SUM("${columns.frutas}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.frutas}",
//   COALESCE(round(toFloat64(SUM("${columns.carnes}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.carnes}",
//   COALESCE(round(toFloat64(SUM("${columns.pescados}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.pescados}",
//   COALESCE(round(toFloat64(SUM("${columns.carnes_e_peixes_industrializados}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.carnes_e_peixes_industrializados}",
//   COALESCE(round(toFloat64(SUM("${columns.aves_e_ovos}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.aves_e_ovos}",
//   COALESCE(round(toFloat64(SUM("${columns.leites_e_derivados}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.leites_e_derivados}",
//   COALESCE(round(toFloat64(SUM("${columns.panificados}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.panificados}",
//   COALESCE(round(toFloat64(SUM("${columns.oleos_e_gorduras}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.oleos_e_gorduras}",
//   COALESCE(round(toFloat64(SUM("${columns.bebidas_e_infusoes}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.bebidas_e_infusoes}",
//   COALESCE(round(toFloat64(SUM("${columns.enlatados_e_conservas}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.enlatados_e_conservas}",
//   COALESCE(round(toFloat64(SUM("${columns.sal_e_condimentos}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.sal_e_condimentos}",
//   COALESCE(round(toFloat64(SUM("${columns.leite_de_coco}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.leite_de_coco}",
//   COALESCE(round(toFloat64(SUM("${columns.atomatado}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.atomatado}",
//   COALESCE(round(toFloat64(SUM("${columns.alho}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.alho}",
//   COALESCE(round(toFloat64(SUM("${columns.sal}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.sal}",
//   COALESCE(round(toFloat64(SUM("${columns.sal_grosso}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.sal_grosso}",
//   COALESCE(round(toFloat64(SUM("${columns.colorau}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.colorau}",
//   COALESCE(round(toFloat64(SUM("${columns.caldo_de_tucupi}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.caldo_de_tucupi}",
//   COALESCE(round(toFloat64(SUM("${columns.fermento}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.fermento}",
//   COALESCE(round(toFloat64(SUM("${columns.maionese}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.maionese}",
//   COALESCE(round(toFloat64(SUM("${columns.vinagre_de_alcool}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.vinagre_de_alcool}",
//   COALESCE(round(toFloat64(SUM("${columns.vinagre}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.vinagre}",
//   COALESCE(round(toFloat64(SUM("${columns.salsa_desidratada}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.salsa_desidratada}",
//   COALESCE(round(toFloat64(SUM("${columns.misso}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.misso}",
//   COALESCE(round(toFloat64(SUM("${columns.caldo_concentrado}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.caldo_concentrado}",
//   COALESCE(round(toFloat64(SUM("${columns.pimenta_em_po}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.pimenta_em_po}",
//   COALESCE(round(toFloat64(SUM("${columns.cominho}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.cominho}",
//   COALESCE(round(toFloat64(SUM("${columns.fondor}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.fondor}",
//   COALESCE(round(toFloat64(SUM("${columns.amaciante_de_carne}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.amaciante_de_carne}",
//   COALESCE(round(toFloat64(SUM("${columns.sal_dietetico}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.sal_dietetico}",
//   COALESCE(round(toFloat64(SUM("${columns.hortela}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.hortela}",
//   COALESCE(round(toFloat64(SUM("${columns.pimenta_do_reino}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.pimenta_do_reino}",
//   COALESCE(round(toFloat64(SUM("${columns.curry}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.curry}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_tucupi_com_pimenta}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_tucupi_com_pimenta}",
//   COALESCE(round(toFloat64(SUM("${columns.sal_amoniaco}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.sal_amoniaco}",
//   COALESCE(round(toFloat64(SUM("${columns.tempero_misto}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.tempero_misto}",
//   COALESCE(round(toFloat64(SUM("${columns.bicarbonato_de_sodio}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.bicarbonato_de_sodio}",
//   COALESCE(round(toFloat64(SUM("${columns.glutamato_monossodico}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.glutamato_monossodico}",
//   COALESCE(round(toFloat64(SUM("${columns.baunilha_em_po}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.baunilha_em_po}",
//   COALESCE(round(toFloat64(SUM("${columns.canela_em_po}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.canela_em_po}",
//   COALESCE(round(toFloat64(SUM("${columns.cravo}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.cravo}",
//   COALESCE(round(toFloat64(SUM("${columns.paprica}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.paprica}",
//   COALESCE(round(toFloat64(SUM("${columns.noz_moscada}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.noz_moscada}",
//   COALESCE(round(toFloat64(SUM("${columns.mostarda}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.mostarda}",
//   COALESCE(round(toFloat64(SUM("${columns.louro}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.louro}",
//   COALESCE(round(toFloat64(SUM("${columns.acafrao_em_po}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.acafrao_em_po}",
//   COALESCE(round(toFloat64(SUM("${columns.gengibre}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.gengibre}",
//   COALESCE(round(toFloat64(SUM("${columns.alfavaca}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.alfavaca}",
//   COALESCE(round(toFloat64(SUM("${columns.oregano}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.oregano}",
//   COALESCE(round(toFloat64(SUM("${columns.alcaparra}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.alcaparra}",
//   COALESCE(round(toFloat64(SUM("${columns.manjerona}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.manjerona}",
//   COALESCE(round(toFloat64(SUM("${columns.coentro}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.coentro}",
//   COALESCE(round(toFloat64(SUM("${columns.alho_em_po}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.alho_em_po}",
//   COALESCE(round(toFloat64(SUM("${columns.cebola_em_po}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.cebola_em_po}",
//   COALESCE(round(toFloat64(SUM("${columns.cheiro_verde_em_po}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.cheiro_verde_em_po}",
//   COALESCE(round(toFloat64(SUM("${columns.pimentao_em_po}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.pimentao_em_po}",
//   COALESCE(round(toFloat64(SUM("${columns.vinagre_de_maca}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.vinagre_de_maca}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_soja}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_soja}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_ingles}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_ingles}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_tartaro}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_tartaro}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_branco}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_branco}",
//   COALESCE(round(toFloat64(SUM("${columns.caldo_de_queijo}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.caldo_de_queijo}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_nao_especificado}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_nao_especificado}",
//   COALESCE(round(toFloat64(SUM("${columns.coalho}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.coalho}",
//   COALESCE(round(toFloat64(SUM("${columns.sal_amargo}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.sal_amargo}",
//   COALESCE(round(toFloat64(SUM("${columns.salvia_em_folha}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.salvia_em_folha}",
//   COALESCE(round(toFloat64(SUM("${columns.erva_doce}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.erva_doce}",
//   COALESCE(round(toFloat64(SUM("${columns.tomilho_em_folha}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.tomilho_em_folha}",
//   COALESCE(round(toFloat64(SUM("${columns.vinagre_de_arroz}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.vinagre_de_arroz}",
//   COALESCE(round(toFloat64(SUM("${columns.vinagre_de_milho}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.vinagre_de_milho}",
//   COALESCE(round(toFloat64(SUM("${columns.gergelim_em_po}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.gergelim_em_po}",
//   COALESCE(round(toFloat64(SUM("${columns.tempero_de_saladas}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.tempero_de_saladas}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_xadrez}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_xadrez}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_funghi}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_funghi}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_alho}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_alho}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_pimenta}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_pimenta}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_madeira}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_madeira}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_para_salada}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_para_salada}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_agridoce}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_agridoce}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_barbecue}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_barbecue}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_frango}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_frango}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_para_carne}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_para_carne}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_temperado_parmesao}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_temperado_parmesao}",
//   COALESCE(round(toFloat64(SUM("${columns.pimenta_calabresa}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.pimenta_calabresa}",
//   COALESCE(round(toFloat64(SUM("${columns.vinagre_de_limao}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.vinagre_de_limao}",
//   COALESCE(round(toFloat64(SUM("${columns.vinagre_balsamico}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.vinagre_balsamico}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_cogumelos}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_cogumelos}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_chimichurri}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_chimichurri}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_pesto}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_pesto}",
//   COALESCE(round(toFloat64(SUM("${columns.alecrim_desidratado}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.alecrim_desidratado}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_vinagrete}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_vinagrete}",
//   COALESCE(round(toFloat64(SUM("${columns.zaatar}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.zaatar}",
//   COALESCE(round(toFloat64(SUM("${columns.furikake}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.furikake}",
//   COALESCE(round(toFloat64(SUM("${columns.wasabi}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.wasabi}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_beterraba}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_beterraba}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_cenoura}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_cenoura}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_cheddar}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_cheddar}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_almeirao}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_almeirao}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_alho_poro_organico}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_alho_poro_organico}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_rucula_organico}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_rucula_organico}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_cebola_organica}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_cebola_organica}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_salsa}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_salsa}",
//   COALESCE(round(toFloat64(SUM("${columns.molho_de_espinafre}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.molho_de_espinafre}",
//   COALESCE(round(toFloat64(SUM("${columns.total_alimentacao_fora_do_domicilio}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.total_alimentacao_fora_do_domicilio}",
//   COALESCE(round(toFloat64(SUM("${columns.refeicao}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.refeicao}",
//   COALESCE(round(toFloat64(SUM("${columns.lanche}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.lanche}",
//   COALESCE(round(toFloat64(SUM("${columns.refrigerante_e_agua_mineral}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.refrigerante_e_agua_mineral}",
//   COALESCE(round(toFloat64(SUM("${columns.cafezinho}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.cafezinho}",
//   COALESCE(round(toFloat64(SUM("${columns.salada_de_frutas}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.salada_de_frutas}",
//   COALESCE(round(toFloat64(SUM("${columns.tapioca_beiju}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.tapioca_beiju}",
//   COALESCE(round(toFloat64(SUM("${columns.acai_emulsao}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.acai_emulsao}",
//   COALESCE(round(toFloat64(SUM("${columns.caldos}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.caldos}",
//   COALESCE(round(toFloat64(SUM("${columns.cha_preparado}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.cha_preparado}",
//   COALESCE(round(toFloat64(SUM("${columns.cerveja}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.cerveja}",
//   COALESCE(round(toFloat64(SUM("${columns.outras_bebidas_alcoolicas}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.outras_bebidas_alcoolicas}",
//   COALESCE(round(toFloat64(SUM("${columns.vinho}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.vinho}",
//   COALESCE(round(toFloat64(SUM("${columns.doces}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.doces}",
//   COALESCE(round(toFloat64(SUM("${columns.biscoito}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.biscoito}",
//   COALESCE(round(toFloat64(SUM("${columns.bala_ou_chiclete}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.bala_ou_chiclete}",
//   COALESCE(round(toFloat64(SUM("${columns.chocolate_e_bombom}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.chocolate_e_bombom}",
//   COALESCE(round(toFloat64(SUM("${columns.sorvete}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.sorvete}",
//   COALESCE(round(toFloat64(SUM("${columns.fruta}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.fruta}",
//   COALESCE(round(toFloat64(SUM("${columns.iogurte}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.iogurte}",
//   COALESCE(round(toFloat64(SUM("${columns.energetico}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.energetico}",
//   COALESCE(round(toFloat64(SUM("${columns.isotonico}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.isotonico}",
//   COALESCE(round(toFloat64(SUM("${columns.achocolatado}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.achocolatado}",
//   COALESCE(round(toFloat64(SUM("${columns.leite_fermentado}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.leite_fermentado}",
// ];


const consumoFinal = [
  COALESCE(round(toFloat64(SUM("${columns.total_alimentacao}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.total_alimentacao}",
  COALESCE(round(toFloat64(SUM("${columns.total_alimentacao_no_domicilio}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.total_alimentacao_no_domicilio}",
  COALESCE(round(toFloat64(SUM("${columns.total_alimentacao_fora_do_domicilio}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.total_alimentacao_fora_do_domicilio}",
  COALESCE(round(toFloat64(SUM("${columns.carnes}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.carnes}",
  COALESCE(round(toFloat64(SUM("${columns.bebidas_e_infusoes}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.bebidas_e_infusoes}",
  COALESCE(round(toFloat64(SUM("${columns.panificados}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.panificados}",
  COALESCE(round(toFloat64(SUM("${columns.leites_e_derivados}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.leites_e_derivados}",
  COALESCE(round(toFloat64(SUM("${columns.aves_e_ovos}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.aves_e_ovos}",
  COALESCE(round(toFloat64(SUM("${columns.frutas}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.frutas}",
  COALESCE(round(toFloat64(SUM("${columns.cereais_leguminosas_e_oleaginosas}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.cereais_leguminosas_e_oleaginosas}",
  COALESCE(round(toFloat64(SUM("${columns.acucares_e_derivados}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.acucares_e_derivados}",
  COALESCE(round(toFloat64(SUM("${columns.carnes_e_peixes_industrializados}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.carnes_e_peixes_industrializados}",
  COALESCE(round(toFloat64(SUM("${columns.tuberculos_raizes_e_legumes}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.tuberculos_raizes_e_legumes}",
  COALESCE(round(toFloat64(SUM("${columns.farinhas_feculas_e_massas}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.farinhas_feculas_e_massas}",
  COALESCE(round(toFloat64(SUM("${columns.sal_e_condimentos}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.sal_e_condimentos}",
  COALESCE(round(toFloat64(SUM("${columns.oleos_e_gorduras}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.oleos_e_gorduras}",
  COALESCE(round(toFloat64(SUM("${columns.refeicao}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.refeicao}",
  COALESCE(round(toFloat64(SUM("${columns.lanche}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.lanche}",
  COALESCE(round(toFloat64(SUM("${columns.cerveja}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.cerveja}",
  COALESCE(round(toFloat64(SUM("${columns.refrigerante_e_agua_mineral}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.refrigerante_e_agua_mineral}",
  COALESCE(round(toFloat64(SUM("${columns.sorvete}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.sorvete}",
  COALESCE(round(toFloat64(SUM("${columns.cafezinho}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.cafezinho}",
  COALESCE(round(toFloat64(SUM("${columns.doces}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.doces}",
  COALESCE(round(toFloat64(SUM("${columns.outras_bebidas_alcoolicas}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.outras_bebidas_alcoolicas}",
  COALESCE(round(toFloat64(SUM("${columns.biscoito}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.biscoito}",
  COALESCE(round(toFloat64(SUM("${columns.acai_emulsao}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.acai_emulsao}",
  COALESCE(round(toFloat64(SUM("${columns.chocolate_e_bombom}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.chocolate_e_bombom}",
  COALESCE(round(toFloat64(SUM("${columns.vinho}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.vinho}",
  COALESCE(round(toFloat64(SUM("${columns.bala_ou_chiclete}")) / toFloat64(SUM(${columns.domicilios_perm}))), 0) "${columns.bala_ou_chiclete}",  
];
